### ISSUE TITLE
Some trees and roads are rendered on the second screen

### ISSUE THREAD

**Issue by t0stiman** [AMacro/RR-Multiscreen#1]
![afbeelding](https://github.com/AMacro/RR-Multiscreen/assets/18124323/89037848-2937-42c7-88c3-23680d5f0adf)

It's not always there, it depends on where I am and in what direction I'm looking.

**Comment by t0stiman** [comment]
![afbeelding](https://github.com/AMacro/RR-Multiscreen/assets/18124323/e74caa4e-dd95-4946-93b1-2794cfcd202e)

Oh, I hadnt seen this before

**Comment by AMacro** [comment]
Yeah, this is a known issue since day one, though I've never seen it as bad as your second screen shot and rarely as bad as your first. I usually have the windows at the top, so I don't notice it.

I've got no idea what causes it or how to fix it, but it's definitely happening on a layer beneath the UI canvas, so not game breaking.

**Comment by AMacro** [comment]
I think I may have found the solution - set a culling mask on the camera.

Seems to have worked for me, could you please confirm the issue is fixed?

[Multiscreen 1.3.2.0.zip](https://github.com/AMacro/RR-Multiscreen/files/14073917/Multiscreen.1.3.2.0.zip)

**Comment by t0stiman** [comment]
Yes, it's fixed. Thanks!
