### ISSUE TITLE
Build 2024.2.2 compatibility

### ISSUE THREAD

**Issue by t0stiman** [AMacro/RR-Multiscreen#2]
mod 🅱roke

![afbeelding](https://github.com/AMacro/RR-Multiscreen/assets/18124323/556c6413-6b4e-4af7-8cd7-2386d0e253f3)

**Comment by AMacro** [comment]
Seems they've removed or changed something in the main menu, will investigate

**Comment by AMacro** [comment]
Seems they changed the class 'SettingsMenu' to 'PreferencesMenu'
Also fixed the error message to be useful, rather than just '{ex}'...
Didn't find any other issues during testing, let me know if you find anything else.

Thanks for the heads up, may not have noticed this for another day or 2 since the NexusMods notification system is so bad.
